<?php
/* This file is part of the Magento Netbanx payment module (iitc).             *
 * Copyright Dave Barker 2009                                                  *
 *                                                                             *
 * The Magento Netbanx payment module (iitc) is free software: you can         *
 * redistribute it and/or modify it under the terms of the GNU General Public  *
 * License as published by the Free Software Foundation, either version 3      *
 * of the License, or (at your option) any later version.                      *
 *                                                                             *
 * the Magento Netbanx payment module (iitc) is distributed in the hope        *
 * that it will be useful, but WITHOUT ANY WARRANTY; without even the implied  *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the   *
 * GNU General Public License for more details.                                *
 *                                                                             *
 * You should have received a copy of the GNU General Public License           *
 * along with the Magento Netbanx payment module (iitc).                       *
 * If not, see <http://www.gnu.org/licenses/>.                                 */

?>


<div class="page-head">
   <h3><?php echo $this->__('Please follow the instructions from NETBANX below to complete your order') ?></h3>
</div>

<?php
   if (!Mage::getStoreConfig('payment/Netbanx/iframe')) {
     echo $this->getLayout()
               ->createBlock('Netbanx/redirect')
               ->toHtml();
   } else {
?>
<iframe style="width: 100%; height: 600px; border: 0px;" src="<?php echo Mage::getUrl('*/*/redirect', array('_secure'=>true)) ?>" id="magentonetbanxiframe" name="magentonetbanxiframe"></iframe>

<?php
}
?>

